name: pokemons
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  assets:
      path: packages/assets
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  navigation:
    path: packages/navigation
  repositories:
    path: packages/repositories
  responsive:
    path: packages/responsive
  shared_preferences: ^2.3.1
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  theme:
    path: packages/theme

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  slang_build_runner: ^3.31.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true