/// Generated file. Do not edit.
///
/// Original: i18n
/// To regenerate, run: `dart run slang`
///
/// Locales: 1
/// Strings: 12
///
/// Built on 2024-06-10 at 01:19 UTC

// coverage:ignore-file
// ignore_for_file: type=lint

import 'package:flutter/widgets.dart';
import 'package:slang/api/translation_overrides.dart';
import 'package:slang/builder/model/build_model_config.dart';
import 'package:slang/builder/model/enums.dart';
import 'package:slang/builder/model/node.dart';
import 'package:slang_flutter/slang_flutter.dart';
export 'package:slang_flutter/slang_flutter.dart';

/// Generated by the "Translation Overrides" feature.
/// This config is needed to recreate the translation model exactly
/// the same way as this file was created.
final _buildConfig = BuildModelConfig(
	fallbackStrategy: FallbackStrategy.none,
	keyCase: null,
	keyMapCase: null,
	paramCase: null,
	stringInterpolation: StringInterpolation.doubleBraces,
	maps: [],
	pluralAuto: PluralAuto.cardinal,
	pluralParameter: 'n',
	pluralCardinal: [],
	pluralOrdinal: [],
	contexts: [],
	interfaces: [], // currently not supported
);

const AppLocale _baseLocale = AppLocale.es;

/// Supported locales, see extension methods below.
///
/// Usage:
/// - LocaleSettings.setLocale(AppLocale.es) // set locale
/// - Locale locale = AppLocale.es.flutterLocale // get flutter locale from enum
/// - if (LocaleSettings.currentLocale == AppLocale.es) // locale check
enum AppLocale with BaseAppLocale<AppLocale, Translations> {
	es(languageCode: 'es', build: Translations.build);

	const AppLocale({required this.languageCode, this.scriptCode, this.countryCode, required this.build}); // ignore: unused_element

	@override final String languageCode;
	@override final String? scriptCode;
	@override final String? countryCode;
	@override final TranslationBuilder<AppLocale, Translations> build;

	/// Gets current instance managed by [LocaleSettings].
	Translations get translations => LocaleSettings.instance.translationMap[this]!;
}

/// Method A: Simple
///
/// No rebuild after locale change.
/// Translation happens during initialization of the widget (call of texts).
/// Configurable via 'translate_var'.
///
/// Usage:
/// String a = texts.someKey.anotherKey;
/// String b = texts['someKey.anotherKey']; // Only for edge cases!
Translations get texts => LocaleSettings.instance.currentTranslations;

/// Method B: Advanced
///
/// All widgets using this method will trigger a rebuild when locale changes.
/// Use this if you have e.g. a settings page where the user can select the locale during runtime.
///
/// Step 1:
/// wrap your App with
/// TranslationProvider(
/// 	child: MyApp()
/// );
///
/// Step 2:
/// final texts = Translations.of(context); // Get texts variable.
/// String a = texts.someKey.anotherKey; // Use texts variable.
/// String b = texts['someKey.anotherKey']; // Only for edge cases!
class TranslationProvider extends BaseTranslationProvider<AppLocale, Translations> {
	TranslationProvider({required super.child}) : super(settings: LocaleSettings.instance);

	static InheritedLocaleData<AppLocale, Translations> of(BuildContext context) => InheritedLocaleData.of<AppLocale, Translations>(context);
}

/// Method B shorthand via [BuildContext] extension method.
/// Configurable via 'translate_var'.
///
/// Usage (e.g. in a widget's build method):
/// context.texts.someKey.anotherKey
extension BuildContextTranslationsExtension on BuildContext {
	Translations get texts => TranslationProvider.of(this).translations;
}

/// Manages all translation instances and the current locale
class LocaleSettings extends BaseFlutterLocaleSettings<AppLocale, Translations> {
	LocaleSettings._() : super(utils: AppLocaleUtils.instance);

	static final instance = LocaleSettings._();

	// static aliases (checkout base methods for documentation)
	static AppLocale get currentLocale => instance.currentLocale;
	static Stream<AppLocale> getLocaleStream() => instance.getLocaleStream();
	static AppLocale setLocale(AppLocale locale, {bool? listenToDeviceLocale = false}) => instance.setLocale(locale, listenToDeviceLocale: listenToDeviceLocale);
	static AppLocale setLocaleRaw(String rawLocale, {bool? listenToDeviceLocale = false}) => instance.setLocaleRaw(rawLocale, listenToDeviceLocale: listenToDeviceLocale);
	static AppLocale useDeviceLocale() => instance.useDeviceLocale();
	@Deprecated('Use [AppLocaleUtils.supportedLocales]') static List<Locale> get supportedLocales => instance.supportedLocales;
	@Deprecated('Use [AppLocaleUtils.supportedLocalesRaw]') static List<String> get supportedLocalesRaw => instance.supportedLocalesRaw;
	static void setPluralResolver({String? language, AppLocale? locale, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver}) => instance.setPluralResolver(
		language: language,
		locale: locale,
		cardinalResolver: cardinalResolver,
		ordinalResolver: ordinalResolver,
	);
	static void overrideTranslations({required AppLocale locale, required FileType fileType, required String content}) => instance.overrideTranslations(locale: locale, fileType: fileType, content: content);
	static void overrideTranslationsFromMap({required AppLocale locale, required bool isFlatMap, required Map map}) => instance.overrideTranslationsFromMap(locale: locale, isFlatMap: isFlatMap, map: map);
}

/// Provides utility functions without any side effects.
class AppLocaleUtils extends BaseAppLocaleUtils<AppLocale, Translations> {
	AppLocaleUtils._() : super(baseLocale: _baseLocale, locales: AppLocale.values, buildConfig: _buildConfig);

	static final instance = AppLocaleUtils._();

	// static aliases (checkout base methods for documentation)
	static AppLocale parse(String rawLocale) => instance.parse(rawLocale);
	static AppLocale parseLocaleParts({required String languageCode, String? scriptCode, String? countryCode}) => instance.parseLocaleParts(languageCode: languageCode, scriptCode: scriptCode, countryCode: countryCode);
	static AppLocale findDeviceLocale() => instance.findDeviceLocale();
	static List<Locale> get supportedLocales => instance.supportedLocales;
	static List<String> get supportedLocalesRaw => instance.supportedLocalesRaw;
	static Translations buildWithOverrides({required AppLocale locale, required FileType fileType, required String content, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver}) => instance.buildWithOverrides(locale: locale, fileType: fileType, content: content, cardinalResolver: cardinalResolver, ordinalResolver: ordinalResolver);
	static Translations buildWithOverridesFromMap({required AppLocale locale, required bool isFlatMap, required Map map, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver}) => instance.buildWithOverridesFromMap(locale: locale, isFlatMap: isFlatMap, map: map, cardinalResolver: cardinalResolver, ordinalResolver: ordinalResolver);
}

// translations

// Path: <root>
class Translations implements BaseTranslations<AppLocale, Translations> {
	/// Returns the current translations of the given [context].
	///
	/// Usage:
	/// final texts = Translations.of(context);
	static Translations of(BuildContext context) => InheritedLocaleData.of<AppLocale, Translations>(context).translations;

	/// You can call this constructor and build your own translation instance of this locale.
	/// Constructing via the enum [AppLocale.build] is preferred.
	/// [AppLocaleUtils.buildWithOverrides] is recommended for overriding.
	Translations.build({Map<String, Node>? overrides, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver})
		: $meta = TranslationMetadata(
		    locale: AppLocale.es,
		    overrides: overrides ?? {},
		    cardinalResolver: cardinalResolver,
		    ordinalResolver: ordinalResolver,
		  ) {
		$meta.setFlatMapFunction(_flatMapFunction);
	}

	/// Metadata for the translations of <es>.
	@override final TranslationMetadata<AppLocale, Translations> $meta;

	/// Access flat map
	dynamic operator[](String key) => $meta.getTranslation(key);

	late final Translations _root = this; // ignore: unused_field

	// Translations
	late final _TranslationsHomeEs home = _TranslationsHomeEs._(_root);
	late final _TranslationsPokemonDetailsEs pokemon_details = _TranslationsPokemonDetailsEs._(_root);
}

// Path: home
class _TranslationsHomeEs {
	_TranslationsHomeEs._(this._root);

	final Translations _root; // ignore: unused_field

	// Translations
	String get findYourPokemon => TranslationOverrides.string(_root.$meta, 'home.findYourPokemon', {}) ?? 'Encuentra tu Pokémon';
	String get search => TranslationOverrides.string(_root.$meta, 'home.search', {}) ?? 'Buscar';
}

// Path: pokemon_details
class _TranslationsPokemonDetailsEs {
	_TranslationsPokemonDetailsEs._(this._root);

	final Translations _root; // ignore: unused_field

	// Translations
	String get height => TranslationOverrides.string(_root.$meta, 'pokemon_details.height', {}) ?? 'Height';
	String get weight => TranslationOverrides.string(_root.$meta, 'pokemon_details.weight', {}) ?? 'Weight';
	late final _TranslationsPokemonDetailsStatsEs stats = _TranslationsPokemonDetailsStatsEs._(_root);
	late final _TranslationsPokemonDetailsMovesEs moves = _TranslationsPokemonDetailsMovesEs._(_root);
}

// Path: pokemon_details.stats
class _TranslationsPokemonDetailsStatsEs {
	_TranslationsPokemonDetailsStatsEs._(this._root);

	final Translations _root; // ignore: unused_field

	// Translations
	String get title => TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.title', {}) ?? 'Stats';
	String get hp => TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.hp', {}) ?? 'HP';
	String get attack => TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.attack', {}) ?? 'Attack';
	String get defense => TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.defense', {}) ?? 'Defense';
	String get specialAttack => TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.specialAttack', {}) ?? 'Sp Atk';
	String get specialDefense => TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.specialDefense', {}) ?? 'Sp Def';
	String get speed => TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.speed', {}) ?? 'Speed';
}

// Path: pokemon_details.moves
class _TranslationsPokemonDetailsMovesEs {
	_TranslationsPokemonDetailsMovesEs._(this._root);

	final Translations _root; // ignore: unused_field

	// Translations
	String get title => TranslationOverrides.string(_root.$meta, 'pokemon_details.moves.title', {}) ?? 'Moves';
}

/// Flat map(s) containing all translations.
/// Only for edge cases! For simple maps, use the map function of this library.

extension on Translations {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'home.findYourPokemon': return TranslationOverrides.string(_root.$meta, 'home.findYourPokemon', {}) ?? 'Encuentra tu Pokémon';
			case 'home.search': return TranslationOverrides.string(_root.$meta, 'home.search', {}) ?? 'Buscar';
			case 'pokemon_details.height': return TranslationOverrides.string(_root.$meta, 'pokemon_details.height', {}) ?? 'Height';
			case 'pokemon_details.weight': return TranslationOverrides.string(_root.$meta, 'pokemon_details.weight', {}) ?? 'Weight';
			case 'pokemon_details.stats.title': return TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.title', {}) ?? 'Stats';
			case 'pokemon_details.stats.hp': return TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.hp', {}) ?? 'HP';
			case 'pokemon_details.stats.attack': return TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.attack', {}) ?? 'Attack';
			case 'pokemon_details.stats.defense': return TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.defense', {}) ?? 'Defense';
			case 'pokemon_details.stats.specialAttack': return TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.specialAttack', {}) ?? 'Sp Atk';
			case 'pokemon_details.stats.specialDefense': return TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.specialDefense', {}) ?? 'Sp Def';
			case 'pokemon_details.stats.speed': return TranslationOverrides.string(_root.$meta, 'pokemon_details.stats.speed', {}) ?? 'Speed';
			case 'pokemon_details.moves.title': return TranslationOverrides.string(_root.$meta, 'pokemon_details.moves.title', {}) ?? 'Moves';
			default: return null;
		}
	}
}
